### ISSUE TITLE
Detailed job report

### ISSUE THREAD

**Issue by tilmankamp** [mozilla/snakepit#102]
Job report that shows short job descriptions similar to the one in "status" report, but lists all jobs so far.
It should support basic filtering and ordering by user, title and times.

**Comment by kdavis-mozilla** [comment]
Maybe instead of showing "all jobs so far" it could have some default, say last 100 jobs, then you could, if you needed, specify that more jobs should be returned.

The only reason I say this is that I could see someone using the command and getting all the jobs for the last three years while really needing jobs for the last month.

Also this opens up a follow on question, should this default be by time, jobs for the last week, or by number, last 100 jobs. I don't know.

**Comment by tilmankamp** [comment]
Yes, I already planned for a limit and default order will be descending by last state change.

**Comment by tilmankamp** [comment]
Fixed through #127
